application: isthehousesitting
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: default.py

- url: /favicon.ico
  static_files: /favicon.ico
  upload: /favicon.ico
  mime_type: image/vnd.microsoft.icon
